name: "Test model and deploy"
run-name: "Run: ${{ github.run_id }}"
on:
  workflow_dispatch:
  push:
    branches:
      - deploy_model
    # paths:
    #   - "model-tensorflow/promoted-model/*"

jobs:
  test-deploy-model:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and setup miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Linux-x86_64.sh
          bash Miniconda3-py310_23.3.1-0-Linux-x86_64.sh -b
          conda init

      - name: Setup environment
        run: |
          conda create -p ./venv python==3.6.8 -y
          conda run -p ./venv pip install -r requirements.txt
          conda run -p ./venv pip install ./model-tensorflow/bin/model-utils

      - name: Run model test
        run: |
          cd model-tensorflow
          conda run -p ../venv mutils test

      - name: Deploy model
        run: |
          cd model-tensorflow
          mkdir converted-model
          conda run -p ../venv tensorflowjs_converter --input_format=keras --output_format=tfjs_graph_model \
          "promoted-model/$(ls ./promoted-model)" \
          converted-mode/
          ls -l converted-model
